In [10]:
import selenium

import pandas as pd

from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

import requests

from selenium.common.exceptions import NoSuchElementException

Q1:Scrape  the  details  of  most  viewed  videos  on  YouTube  from  Wikipedia.  
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:  
A) Rank   
B) Name   
C) Artist   
D) Upload date   
E) Views

In [2]:
driver = webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [11]:
data =[]

table= driver.find_element(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[1]/tbody')

for tr in table.find_elements(By.XPATH,'//tr'):
    row = [item.text for item in tr.find_elements(By.XPATH,'.//td')]
    data.append(row)
           
data

[[],
 ['"Baby Shark Dance"[7]',
  "Pinkfong Baby Shark - Kids' Songs & Stories",
  '14.66',
  'June 17, 2016',
  '[A]'],
 ['"Despacito"[10]', 'Luis Fonsi', '8.47', 'January 12, 2017', '[B]'],
 ['"Johny Johny Yes Papa"[18]',
  "LooLoo Kids - Nursery Rhymes and Children's Songs",
  '6.92',
  'October 8, 2016',
  ''],
 ['"Bath Song"[19]', 'Cocomelon - Nursery Rhymes', '6.75', 'May 2, 2018', ''],
 ['"See You Again"[20]', 'Wiz Khalifa', '6.30', 'April 6, 2015', '[C]'],
 ['"Shape of You"[25]', 'Ed Sheeran', '6.28', 'January 30, 2017', '[D]'],
 ['"Wheels on the Bus"[28]',
  'Cocomelon - Nursery Rhymes',
  '6.22',
  'May 24, 2018',
  ''],
 ['"Phonics Song with Two Words"[29]',
  'ChuChu TV Nursery Rhymes & Kids Songs',
  '5.84',
  'March 6, 2014',
  ''],
 ['"Uptown Funk"[30]', 'Mark Ronson', '5.25', 'November 19, 2014', ''],
 ['"Gangnam Style"[31]', 'Psy', '5.20', 'July 15, 2012', '[E]'],
 ['"Learning Colors – Colorful Eggs on a Farm"[36]',
  'Miroshka TV',
  '5.13',
  'February 27, 2018',
  ''],
 ['"Dame Tu Cosita"[37]', 'Ultra Records', '4.68', 'April 5, 2018', ''],
 ['"Axel F"[38]', 'Crazy Frog', '4.60', 'June 16, 2009', ''],
 ['"Masha and the Bear – Recipe for Disaster"[39]',
  'Get Movies',
  '4.60',
  'January 31, 2012',
  ''],
 ['"Baa Baa Black Sheep"[40]',
  'Cocomelon - Nursery Rhymes',
  '4.10',
  'June 25, 2018',
  ''],
 ['"Lakdi Ki Kathi"[41]', 'Jingle Toons', '4.07', 'June 14, 2018', ''],
 ['"Sugar"[42]', 'Maroon 5', '4.06', 'January 14, 2015', ''],
 ['"Counting Stars"[43]', 'OneRepublic', '4.03', 'May 31, 2013', ''],
 ['"Roar"[44]', 'Katy Perry', '4.01', 'September 5, 2013', ''],
 ['"Waka Waka (This Time for Africa)"[45]',
  'Shakira',
  '3.96',
  'June 4, 2010',
  ''],
 ['"Shree Hanuman Chalisa"[46]',
  'T-Series Bhakti Sagar',
  '3.90',
  'May 10, 2011',
  ''],
 ['"Humpty the train on a fruits ride"[47]',
  'Kiddiestv Hindi - Nursery Rhymes & Kids Songs',
  '3.84',
  'January 26, 2018',
  ''],
 ['"Sorry"[48]', 'Justin Bieber', '3.82', 'October 22, 2015', ''],
 ['"Thinking Out Loud"[49]', 'Ed Sheeran', '3.78', 'October 7, 2014', ''],
 ['"Perfect"[50]', 'Ed Sheeran', '3.75', 'November 9, 2017', ''],
 ['"Dark Horse"[51]', 'Katy Perry', '3.74', 'February 20, 2014', ''],
 ['"Let Her Go"[52]', 'Passenger', '3.68', 'July 25, 2012', ''],
 ['"Faded"[53]', 'Alan Walker', '3.65', 'December 3, 2015', ''],
 ['"Girls Like You"[54]', 'Maroon 5', '3.62', 'May 31, 2018', ''],
 ['"Lean On"[55]', 'Major Lazer Official', '3.62', 'March 22, 2015', ''],
 [],
 [],
 ['"Baby Shark Dance"[7]',
  "Pinkfong Baby Shark - Kids' Songs & Stories",
  '7,046,700,000',
  'June 17, 2016',
  'November 2, 2020',
  '1600',
  '1,334',
  '',
  '',
  ''],
 ['"Despacito"[10]',
  'Luis Fonsi',
  '2,993,700,000',
  'January 12, 2017',
  'August 4, 2017',
  '206',
  '1,186',
  '',
  '[11]',
  '[B]'],
 ['"See You Again"[20]',
  'Wiz Khalifa',
  '2,894,000,000',
  'April 6, 2015',
  'July 10, 2017',
  '826',
  '25',
  '',
  '[21]',
  ''],
 ['"Gangnam Style"⁂[31]',
  'Psy',
  '803,700,000',
  'July 15, 2012',
  'November 24, 2012',
  '134',
  '1,689',
  '',
  '[32]',
  '[E]'],
 ['"Baby"*[69]',
  'Justin Bieber',
  '245,400,000',
  'February 19, 2010',
  'July 16, 2010',
  '149',
  '862',
  '',
  '[70]',
  '[F]'],
 ['"Bad Romance"[73]',
  'Lady Gaga',
  '178,400,000',
  'November 24, 2009',
  'April 14, 2010',
  '143',
  '93',
  '',
  '[74]',
  '[G]'],
 ['"Charlie Bit My Finger"[77]',
  'HDCYT',
  '128,900,000',
  'May 22, 2007',
  'October 25, 2009',
  '887',
  '171',
  'July 2021 (made available again January 2024)',
  '[78]',
  ''],
 ['"Evolution of Dance"[79]',
  'Judson Laipply',
  '118,900,000',
  'April 6, 2006',
  'May 2, 2009',
  '1062',
  '176',
  '',
  '[80]',
  ''],
 ['"Girlfriend"‡[81][82]',
  'RCA Records',
  '92,600,000',
  'February 27, 2007',
  'July 17, 2008',
  '508',
  '289',
  'November 2009[83]',
  '[84]',
  '[H]'],
 ['"Evolution of Dance"[79]',
  'Judson Laipply',
  '78,400,000',
  'April 6, 2006',
  'March 15, 2008',
  '651',
  '124',
  '',
  '[86]',
  ''],
 ['"Music Is My Hot Hot Sex"‡[87]',
  'CLARUSBARTEL72',
  '76,600,000',
  'April 9, 2007',
  'March 1, 2008',
  '327',
  '14',
  'March 15, 2008[88]',
  '[89]',
  '[I]'],
 ['"Evolution of Dance"*[79]',
  'Judson Laipply',
  '10,600,000',
  'April 6, 2006',
  'May 19, 2006',
  '16',
  '652',
  '',
  '[91]',
  '[J]'],
 ['"Pokémon Theme Music Video"‡[92]',
  'Smosh',
  '4,300,000',
  'November 28, 2005',
  'March 12, 2006',
  '105',
  '68',
  'June 2007[93]',
  '[94]',
  '[K]'],
 ['"Myspace – The Movie"‡[97][98]',
  'eggtea',
  '2,700,000',
  'January 31, 2006',
  'February 18, 2006',
  '18',
  '22',
  'mid-2006[99]',
  '[100]',
  ''],
 ['"Phony Photo Booth"‡[101]',
  'mugenized',
  '3,400,000',
  'December 1, 2005',
  'January 21, 2006',
  '50',
  '28',
  'February 14 to 18, 2006[102]',
  '[103]',
  '[L]'],
 ['"The Chronic of Narnia Rap"‡[107]',
  'youtubedude',
  '2,300,000',
  'December 18, 2005',
  'January 9, 2006',
  '22',
  '12',
  'February 14 to 17, 2006[108]',
  '[109]',
  ''],
 ['"Ronaldinho: Touch of Gold"‡*[110]',
  'Nikesoccer',
  '255,000',
  'October 21, 2005',
  'October 31, 2005',
  '10',
  '70',
  'July to August 2009[111]',
  '[112]',
  '[M]'],
 ['"I/O Brush"‡*[116]',
  'larfus',
  '247,000',
  'October 5, 2005',
  'October 29, 2005',
  '24',
  '2',
  'January to April 2007[117]',
  '[118]',
  ''],
 [],
 [],
 [''],
 ['', '', ''],
 [''],
 [''],
 [''],
 ['', '', ''],
 [''],
 [''],
 [''],
 [''],
 [''],
 [''],
 [''],
 [],
 [''],
 ['']]

In [ ]:
Q2:Scrape the details team India’s international fixtures from bcci.tv.   
Url = https://www.bcci.tv/.   
You need to find following details:   
A) Series   
B) Place   
C) Date   
D) Time

In [26]:
driver= webdriver.Chrome()
driver.get('https://www.bcci.tv/')

In [27]:
fixtures = driver.find_element(By.XPATH,'/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
fixtures.click()
time.sleep(2)

In [28]:
series=[]
place=[]
date=[]
time=[]

In [33]:
more= driver.find_element(By.XPATH,'//div[@class="col-lg-12 col-md-12 col-sm-12"]/button')
more.click()

In [34]:
series_name = driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')

for i in series_name:
    series_name=i.text
    series.append(series_name)

In [35]:
len(series)

35

In [36]:
dates = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')

for i in dates:
    dates=i.text
    date.append(dates)
    
places = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')

for i in places:
    places=i.text
    place.append(places)
    
times= driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in times:
    times=i.text
    time.append(times)

In [37]:
data= pd.DataFrame({'Series_Name':series,'Date':date,'Place':place,'Time':time})

In [38]:
data

,Series_Name,Date,Place,Time
0,South Africa Women Tour Of India T20 Series 2024,5 Jul,Chennai,19:00 IST
1,India Tour Of Zimbabwe T20I Series 2024,6 Jul,Harare,16:30 IST
2,India Tour Of Zimbabwe T20I Series 2024,7 Jul,Harare,16:30 IST
3,South Africa Women Tour Of India T20 Series 2024,7 Jul,Chennai,19:00 IST
4,South Africa Women Tour Of India T20 Series 2024,9 Jul,Chennai,19:00 IST
5,India Tour Of Zimbabwe T20I Series 2024,10 Jul,Harare,16:30 IST
6,India Tour Of Zimbabwe T20I Series 2024,13 Jul,Harare,16:30 IST
7,India Tour Of Zimbabwe T20I Series 2024,14 Jul,Harare,16:30 IST
8,Asia Cup Women T20 2024,19 Jul,Dambulla,19:00 IST
9,Asia Cup Women T20 2024,21 Jul,Dambulla,14:00 IST
10,Asia Cup Women T20 2024,23 Jul,Dambulla,19:00 IST
11,Bangladesh Tour Of India Test Series 2024,19 Sep,Chennai,9:30
12,Bangladesh Tour Of India Test Series 2024,27 Sep,Kanpur,9:30
13,ICC Womens T20 World Cup 2024,4 Oct,Sylhet,18:30 IST
14,ICC Womens T20 World Cup 2024,6 Oct,Sylhet,18:30 IST
15,Bangladesh Tour Of India T20 Series 2024,6 Oct,Dharamsala,19:00 IST
16,ICC Womens T20 World Cup 2024,9 Oct,Sylhet,18:30 IST
17,Bangladesh Tour Of India T20 Series 2024,9 Oct,Delhi,19:00 IST
18,Bangladesh Tour Of India T20 Series 2024,12 Oct,Hyderabad,19:00 IST
19,ICC Womens T20 World Cup 2024,13 Oct,Sylhet,18:30 IST
20,New Zealand Tour Of India Test Series 2024,16 Oct,Bengaluru,9:30 IST
21,New Zealand Tour Of India Test Series 2024,24 Oct,Pune,9:30 IST
22,New Zealand Tour Of India Test Series 2024,1 Nov,Mumbai,9:30 IST
23,India Tour Of South Africa T20 Series 2024,8 Nov,Durban,20:00
24,India Tour Of South Africa T20 Series 2024,10 Nov,Gqeberha,20:00
25,India Tour Of South Africa T20 Series 2024,13 Nov,Centurion,20:00
26,India Tour Of South Africa T20 Series 2024,16 Nov,Johannesburg,20:00
27,England Tour Of India T20 Series 2025,22 Jan,Chennai,19:00 IST
28,England Tour Of India T20 Series 2025,25 Jan,Kolkata,19:00 IST
29,England Tour Of India T20 Series 2025,28 Jan,Rajkot,19:00 IST
30,England Tour Of India T20 Series 2025,31 Jan,Pune,19:00 IST
31,England Tour Of India T20 Series 2025,2 Feb,Mumbai,19:00 IST
32,England Tour Of India ODI Series 2025,6 Feb,Nagpur,13:30
33,England Tour Of India ODI Series 2025,9 Feb,Cuttack,13:30
34,England Tour Of India ODI Series 2025,12 Feb,Ahmedabad,13:30

In [ ]:
Q3:Scrape the details of State-wise GDP of India from statisticstime.com.   
Url = http://statisticstimes.com/   
You have to find following details: A) Rank   
B) State   
C) GSDP(18-19)- at current prices   
D) GSDP(19-20)- at current prices   
E) Share(18-19)   
F) GDP($ billion)

In [54]:
driver= webdriver.Chrome()
driver.get('http://statisticstimes.com/')

In [64]:
economy =driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]')
economy.click()

india = driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
india.click()

In [65]:
gdp= driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')

gdp.click()

In [66]:
data =[]

table= driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody')

for tr in table.find_elements(By.XPATH,'//tr'):
    row = [item.text for item in tr.find_elements(By.XPATH,'.//td')]
    data.append(row)
           
data

[['Source', 'Ministry of Statistics and Programme Implementation (17)'],
 ['Date', '04 Apr 2024'],
 [],
 [],
 ['1',
  'Maharashtra',
  '-',
  '-',
  '3,108,022',
  '13.17%',
  '414.928',
  '-',
  '-',
  '2,027,971'],
 ['2',
  'Tamil Nadu',
  '2,700,109',
  '2,364,514',
  '2,071,286',
  '8.78%',
  '276.522',
  '1,572,601',
  '1,453,321',
  '1,343,287'],
 ['3',
  'Karnataka',
  '2,500,733',
  '2,269,995',
  '1,978,094',
  '8.38%',
  '264.080',
  '1,423,229',
  '1,335,052',
  '1,235,377'],
 ['4',
  'Uttar Pradesh',
  '2,547,861',
  '2,258,040',
  '1,975,595',
  '8.37%',
  '263.747',
  '1,423,358',
  '1,318,027',
  '1,200,093'],
 ['5',
  'Gujarat',
  '-',
  '2,230,609',
  '1,928,683',
  '8.17%',
  '257.484',
  '-',
  '1,475,629',
  '1,365,922'],
 ['6',
  'West Bengal',
  '1,700,939',
  '1,531,758',
  '1,329,238',
  '5.63%',
  '177.456',
  '904,088',
  '839,805',
  '787,439'],
 ['7',
  'Rajasthan',
  '1,524,030',
  '1,365,849',
  '1,193,489',
  '5.06%',
  '159.334',
  '842,621',
  '784,655',
  '727,805'],
 ['8',
  'Andhra Pradesh',
  '1,439,674',
  '1,303,524',
  '1,148,471',
  '4.87%',
  '153.324',
  '820,894',
  '764,685',
  '722,727'],
 ['9',
  'Telangana',
  '1,463,960',
  '1,308,034',
  '1,124,204',
  '4.76%',
  '150.084',
  '767,936',
  '715,157',
  '669,229'],
 ['10',
  'Madhya Pradesh',
  '1,363,327',
  '1,246,471',
  '1,092,964',
  '4.63%',
  '145.913',
  '660,363',
  '622,908',
  '584,470'],
 ['11',
  'Kerala',
  '-',
  '1,046,188',
  '934,542',
  '3.96%',
  '124.764',
  '-',
  '616,189',
  '578,057'],
 ['12',
  'Delhi',
  '1,107,746',
  '1,014,688',
  '881,336',
  '3.73%',
  '117.660',
  '672,247',
  '625,981',
  '580,396'],
 ['13',
  'Haryana',
  '1,095,535',
  '984,055',
  '868,905',
  '3.68%',
  '116.001',
  '634,027',
  '587,198',
  '544,317'],
 ['14',
  'Odisha',
  '832,790',
  '753,177',
  '662,886',
  '2.81%',
  '88.497',
  '503,871',
  '464,574',
  '430,541'],
 ['15',
  'Bihar',
  '-',
  '751,396',
  '650,302',
  '2.76%',
  '86.817',
  '-',
  '442,473',
  '399,930'],
 ['16',
  'Punjab',
  '736,423',
  '676,164',
  '617,192',
  '2.62%',
  '82.397',
  '493,283',
  '462,053',
  '434,261'],
 ['17',
  'Assam',
  '565,401',
  '493,167',
  '411,454',
  '1.74%',
  '54.930',
  '318,559',
  '300,799',
  '278,835'],
 ['18',
  'Chhattisgarh',
  '505,887',
  '464,399',
  '410,525',
  '1.74%',
  '54.806',
  '321,945',
  '302,119',
  '280,609'],
 ['19',
  'Jharkhand',
  '-',
  '393,722',
  '358,863',
  '1.52%',
  '47.909',
  '-',
  '259,800',
  '243,348'],
 ['20',
  'Uttarakhand',
  '346,206',
  '303,781',
  '267,143',
  '1.13%',
  '35.664',
  '213,378',
  '198,341',
  '184,274'],
 ['21',
  'Jammu & Kashmir',
  '246,465',
  '224,226',
  '193,352',
  '0.82%',
  '25.813',
  '139,171',
  '129,573',
  '119,174'],
 ['22',
  'Himachal Pradesh',
  '207,430',
  '191,728',
  '172,162',
  '0.73%',
  '22.984',
  '142,800',
  '133,372',
  '124,770'],
 ['23',
  'Goa',
  '-',
  '93,672',
  '84,266',
  '0.36%',
  '11.250',
  '-',
  '59,867',
  '55,342'],
 ['24',
  'Tripura',
  '-',
  '72,636',
  '62,550',
  '0.27%',
  '8.351',
  '-',
  '42,997',
  '39,487'],
 ['25',
  'Chandigarh',
  '-',
  '54,285',
  '46,096',
  '0.20%',
  '6.154',
  '-',
  '33,879',
  '30,587'],
 ['26',
  'Puducherry',
  '-',
  '49,643',
  '43,810',
  '0.19%',
  '5.849',
  '-',
  '28,849',
  '27,131'],
 ['27',
  'Meghalaya',
  '47,381',
  '42,697',
  '38,785',
  '0.16%',
  '5.178',
  '26,524',
  '25,209',
  '24,267'],
 ['28',
  'Sikkim',
  '-',
  '42,756',
  '37,557',
  '0.16%',
  '5.014',
  '-',
  '22,144',
  '20,728'],
 ['29', 'Manipur', '-', '-', '36,594', '0.16%', '4.885', '-', '-', '20,515'],
 ['30',
  'Arunachal Pradesh',
  '-',
  '39,630',
  '34,775',
  '0.15%',
  '4.643',
  '-',
  '21,085',
  '19,707'],
 ['31',
  'Nagaland',
  '-',
  '35,643',
  '31,038',
  '0.13%',
  '4.144',
  '-',
  '18,993',
  '17,336'],
 ['32', 'Mizoram', '-', '-', '27,824', '0.12%', '3.715', '-', '-', '18,494'],
 ['33',
  'Andaman & Nicobar Islands',
  '-',
  '-',
  '10,371',
  '0.04%',
  '1.385',
  '-',
  '-',
  '7,172'],
 ['',
  'India',
  '29,389,686',
  '26,949,646',
  '23,597,399',
  '',
  '3,150',
  '17,290,281',
  '16,071,429',
  '15,021,846'],
 [],
 [],
 ['1', 'Maharashtra', '-', '-', '2,690,525', '13.03%', '-', '-', '1,731,189'],
 ['2',
  'Tamil Nadu',
  '2,417,237',
  '2,115,510',
  '1,854,109',
  '8.98%',
  '1,384,921',
  '1,279,878',
  '1,182,919'],
 ['3',
  'Karnataka',
  '2,261,867',
  '2,055,658',
  '1,790,456',
  '8.67%',
  '1,263,925',
  '1,187,557',
  '1,098,510'],
 ['4',
  'Uttar Pradesh',
  '2,217,055',
  '1,962,865',
  '1,715,328',
  '8.31%',
  '1,206,156',
  '1,116,011',
  '1,014,396'],
 ['5',
  'Gujarat',
  '-',
  '1,946,334',
  '1,700,504',
  '8.23%',
  '-',
  '1,301,070',
  '1,198,007'],
 ['6',
  'West Bengal',
  '1,531,371',
  '1,378,859',
  '1,199,587',
  '5.81%',
  '791,144',
  '735,049',
  '692,592'],
 ['7',
  'Rajasthan',
  '1,366,626',
  '1,222,507',
  '1,068,864',
  '5.18%',
  '737,042',
  '686,211',
  '637,616'],
 ['8',
  'Andhra Pradesh',
  '1,291,518',
  '1,167,107',
  '1,030,465',
  '4.99%',
  '723,343',
  '672,455',
  '636,219'],
 ['9',
  'Telangana',
  '1,326,022',
  '1,184,237',
  '1,017,859',
  '4.93%',
  '679,552',
  '633,091',
  '591,472'],
 ['10',
  'Madhya Pradesh',
  '1,242,883',
  '1,137,254',
  '993,235',
  '4.81%',
  '579,234',
  '546,005',
  '512,117'],
 ['11',
  'Kerala',
  '-',
  '933,564',
  '825,010',
  '3.99%',
  '-',
  '564,164',
  '528,323'],
 ['12',
  'Delhi',
  '997,171',
  '911,639',
  '782,570',
  '3.79%',
  '590,836',
  '548,826',
  '507,595'],
 ['13',
  'Haryana',
  '985,877',
  '885,029',
  '778,885',
  '3.77%',
  '561,368',
  '519,135',
  '480,417'],
 ['14',
  'Bihar',
  '-',
  '681,761',
  '589,712',
  '2.86%',
  '-',
  '394,114',
  '356,057'],
 ['15',
  'Odisha',
  '749,809',
  '670,196',
  '579,905',
  '2.81%',
  '443,233',
  '403,936',
  '369,904'],
 ['16',
  'Punjab',
  '639,252',
  '588,712',
  '540,097',
  '2.62%',
  '424,857',
  '399,400',
  '376,909'],
 ['17',
  'Assam',
  '487,584',
  '428,072',
  '366,359',
  '1.77%',
  '288,842',
  '264,089',
  '246,203'],
 ['18',
  'Chhattisgarh',
  '447,682',
  '412,494',
  '365,028',
  '1.77%',
  '279,803',
  '263,839',
  '245,947'],
 ['19',
  'Jharkhand',
  '-',
  '360,689',
  '325,830',
  '1.58%',
  '-',
  '235,685',
  '219,234'],
 ['20',
  'Uttarakhand',
  '304,592',
  '267,653',
  '235,376',
  '1.14%',
  '186,484',
  '173,280',
  '160,921'],
 ['21',
  'Jammu & Kashmir',
  '200,046',
  '181,383',
  '156,907',
  '0.76%',
  '108,830',
  '100,849',
  '92,690'],
 ['22',
  'Himachal Pradesh',
  '176,164',
  '163,062',
  '145,182',
  '0.70%',
  '120,733',
  '112,633',
  '105,500'],
 ['23', 'Goa', '-', '83,711', '74,305', '0.36%', '-', '52,426', '47,901'],
 ['24', 'Tripura', '-', '65,808', '56,226', '0.27%', '-', '37,917', '34,851'],
 ['25',
  'Chandigarh',
  '-',
  '48,261',
  '41,011',
  '0.20%',
  '-',
  '29,957',
  '26,985'],
 ['26',
  'Puducherry',
  '-',
  '44,809',
  '39,787',
  '0.19%',
  '-',
  '25,652',
  '24,136'],
 ['27',
  'Meghalaya',
  '42,214',
  '37,925',
  '34,441',
  '0.17%',
  '23,063',
  '21,905',
  '21,096'],
 ['28', 'Manipur', '-', '-', '32,874', '0.16%', '-', '-', '17,810'],
 ['29', 'Sikkim', '-', '35,670', '31,519', '0.15%', '-', '17,832', '16,764'],
 ['30',
  'Arunachal Pradesh',
  '-',
  '35,555',
  '31,420',
  '0.15%',
  '-',
  '18,273',
  '17,196'],
 ['31', 'Nagaland', '-', '30,957', '26,924', '0.13%', '-', '14,307', '13,222'],
 ['32', 'Mizoram', '-', '-', '24,293', '0.12%', '-', '-', '15,847'],
 ['33',
  'Andaman & Nicobar Islands',
  '-',
  '-',
  '9,209',
  '0.04%',
  '-',
  '-',
  '6,558'],
 ['',
  'India',
  '25,561,438',
  '23,439,442',
  '20,652,786',
  '',
  '14,805,736',
  '13,746,502',
  '12,872,132']]

In [ ]:
Q4:Scrape the details of trending repositories on Github.com.   
Url = https://github.com/   
You have to find the following details:   
A) Repository title   
B) Repository description   
C) Contributors count   
D) Language used

In [67]:
driver = webdriver.Chrome()

driver.get('https://github.com/')

In [70]:
source = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[4]/button')
source.click()
repo = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[4]/div/div[3]/ul/li[2]/a')
repo.click()

In [71]:
repo_title=[]
repo_descrip=[]
conti_count=[]
lang_used=[]

In [73]:
repository_title =driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a')
for i in repository_title:
    repository_title=i.text
    repo_title.append(repository_title)
repo_title

['microsoft / generative-ai-for-beginners',
 'Asabeneh / 30-Days-Of-Python',
 'goldmansachs / gs-quant',
 'WerWolv / ImHex',
 'ClayAmore / ER-Save-Editor',
 'pedroslopez / whatsapp-web.js',
 'cuixueshe / earthworm',
 'projectdiscovery / nuclei-templates',
 'actualbudget / actual-server',
 'moby / moby',
 'starship / starship',
 'Azure / azure-sdk-for-net',
 'LizardByte / Sunshine',
 'facebook / react-native',
 'iam-veeramalla / aws-devops-zero-to-hero',
 'restic / restic',
 'NVIDIA / gpu-operator']

In [74]:
len(repo_title)

17

In [75]:
description= driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in description:
    description=i.text
    repo_descrip.append(description)
len(repo_descrip)

17

In [76]:
contribution = driver.find_elements(By.XPATH,'//span[@class="d-inline-block mr-3"]')
for i in contribution:
    contribution=i.text
    conti_count.append(contribution)
len(conti_count)

17

In [77]:
langs = driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
for i in langs:
    langs=i.text
    lang_used.append(langs)
len(lang_used)

17

In [79]:
data = pd.DataFrame({'Repository_title':repo_title,'Repository_description':repo_descrip,'Contributors_count':conti_count,
                      'Language_used':lang_used})
data

,Repository_title,Repository_description,Contributors_count,Language_used
0,microsoft / generative-ai-for-beginners,"18 Lessons, Get Started Building with Generati...",Built by,Jupyter Notebook
1,Asabeneh / 30-Days-Of-Python,30 days of Python programming challenge is a s...,Built by,Python
2,goldmansachs / gs-quant,Python toolkit for quantitative finance,Built by,Jupyter Notebook
3,WerWolv / ImHex,"🔍 A Hex Editor for Reverse Engineers, Programm...",Built by,C++
4,ClayAmore / ER-Save-Editor,Elden Ring Save Editor. Compatible with PC and...,Built by,Rust
5,pedroslopez / whatsapp-web.js,A WhatsApp client library for NodeJS that conn...,Built by,JavaScript
6,cuixueshe / earthworm,Learning English through the method of constru...,Built by,TypeScript
7,projectdiscovery / nuclei-templates,Community curated list of templates for the nu...,Built by,JavaScript
8,actualbudget / actual-server,Actual's server,Built by,JavaScript
9,moby / moby,The Moby Project - a collaborative project for...,Built by,Go
10,starship / starship,"☄🌌️ The minimal, blazing-fast, and infinitely ...",Built by,Rust
11,Azure / azure-sdk-for-net,This repository is for active development of t...,Built by,C#
12,LizardByte / Sunshine,Self-hosted game stream host for Moonlight.,Built by,C++
13,facebook / react-native,A framework for building native applications u...,Built by,C++
14,iam-veeramalla / aws-devops-zero-to-hero,AWS zero to hero repo for devops engineers to ...,Built by,Python
15,restic / restic,"Fast, secure, efficient backup program",Built by,Go
16,NVIDIA / gpu-operator,NVIDIA GPU Operator creates/configures/manages...,Built by,Go

In [ ]:
Q5:Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/  You have to find the 
following details:   
A) Song name   
B) Artist name   
C) Last week rank   
D) Peak rank   
E) Weeks on board

In [2]:
driver = webdriver.Chrome()
driver.get('https:/www.billboard.com/')

In [3]:
charts = driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
charts.click()

In [4]:
top_songs = driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a')
top_songs.click()

In [ ]:
data=[]

table= driver.find_element(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for div in table.find_elements(By.XPATH,'//div'):
    row = [item.text for item in div.find_elements(By.XPATH,'//ul')]
    data.append(row)

In [6]:
data

['1\nI Had Some Help\nPost Malone Featuring Morgan Wallen\n2\n1\n7']

In [ ]:
Q6:Scrape the details of Highest selling novels.   
A) Book name   
B) Author name   
C) Volumes sold   
D) Publisher   
E) Genre   
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [11]:
driver = webdriver.Chrome()

driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [12]:
data =[]

table= driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody')

for tr in table.find_elements(By.XPATH,'//tr'):
    row = [item.text for item in tr.find_elements(By.XPATH,'.//td')]
    data.append(row)
           
data

[[],
 ['SOURCE: NIELSEN BOOK SCAN'],
 ['1',
  'Da Vinci Code,The',
  'Brown, Dan',
  '5,094,805',
  'Transworld',
  'Crime, Thriller & Adventure'],
 ['2',
  'Harry Potter and the Deathly Hallows',
  'Rowling, J.K.',
  '4,475,152',
  'Bloomsbury',
  "Children's Fiction"],
 ['3',
  "Harry Potter and the Philosopher's Stone",
  'Rowling, J.K.',
  '4,200,654',
  'Bloomsbury',
  "Children's Fiction"],
 ['4',
  'Harry Potter and the Order of the Phoenix',
  'Rowling, J.K.',
  '4,179,479',
  'Bloomsbury',
  "Children's Fiction"],
 ['5',
  'Fifty Shades of Grey',
  'James, E. L.',
  '3,758,936',
  'Random House',
  'Romance & Sagas'],
 ['6',
  'Harry Potter and the Goblet of Fire',
  'Rowling, J.K.',
  '3,583,215',
  'Bloomsbury',
  "Children's Fiction"],
 ['7',
  'Harry Potter and the Chamber of Secrets',
  'Rowling, J.K.',
  '3,484,047',
  'Bloomsbury',
  "Children's Fiction"],
 ['8',
  'Harry Potter and the Prisoner of Azkaban',
  'Rowling, J.K.',
  '3,377,906',
  'Bloomsbury',
  "Children's Fiction"],
 ['9',
  'Angels and Demons',
  'Brown, Dan',
  '3,193,946',
  'Transworld',
  'Crime, Thriller & Adventure'],
 ['10',
  "Harry Potter and the Half-blood Prince:Children's Edition",
  'Rowling, J.K.',
  '2,950,264',
  'Bloomsbury',
  "Children's Fiction"],
 ['11',
  'Fifty Shades Darker',
  'James, E. L.',
  '2,479,784',
  'Random House',
  'Romance & Sagas'],
 ['12',
  'Twilight',
  'Meyer, Stephenie',
  '2,315,405',
  'Little, Brown Book',
  'Young Adult Fiction'],
 ['13',
  'Girl with the Dragon Tattoo,The:Millennium Trilogy',
  'Larsson, Stieg',
  '2,233,570',
  'Quercus',
  'Crime, Thriller & Adventure'],
 ['14',
  'Fifty Shades Freed',
  'James, E. L.',
  '2,193,928',
  'Random House',
  'Romance & Sagas'],
 ['15',
  'Lost Symbol,The',
  'Brown, Dan',
  '2,183,031',
  'Transworld',
  'Crime, Thriller & Adventure'],
 ['16',
  'New Moon',
  'Meyer, Stephenie',
  '2,152,737',
  'Little, Brown Book',
  'Young Adult Fiction'],
 ['17',
  'Deception Point',
  'Brown, Dan',
  '2,062,145',
  'Transworld',
  'Crime, Thriller & Adventure'],
 ['18',
  'Eclipse',
  'Meyer, Stephenie',
  '2,052,876',
  'Little, Brown Book',
  'Young Adult Fiction'],
 ['19',
  'Lovely Bones,The',
  'Sebold, Alice',
  '2,005,598',
  'Pan Macmillan',
  'General & Literary Fiction'],
 ['20',
  'Curious Incident of the Dog in the Night-time,The',
  'Haddon, Mark',
  '1,979,552',
  'Random House',
  'General & Literary Fiction'],
 ['21',
  'Digital Fortress',
  'Brown, Dan',
  '1,928,900',
  'Transworld',
  'Crime, Thriller & Adventure'],
 ['22',
  'Short History of Nearly Everything,A',
  'Bryson, Bill',
  '1,852,919',
  'Transworld',
  'Popular Science'],
 ['23',
  'Girl Who Played with Fire,The:Millennium Trilogy',
  'Larsson, Stieg',
  '1,814,784',
  'Quercus',
  'Crime, Thriller & Adventure'],
 ['24',
  'Breaking Dawn',
  'Meyer, Stephenie',
  '1,787,118',
  'Little, Brown Book',
  'Young Adult Fiction'],
 ['25',
  'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
  'Carle, Eric',
  '1,783,535',
  'Penguin',
  'Picture Books'],
 ['26',
  'Gruffalo,The',
  'Donaldson, Julia',
  '1,781,269',
  'Pan Macmillan',
  'Picture Books'],
 ['27',
  "Jamie's 30-Minute Meals",
  'Oliver, Jamie',
  '1,743,266',
  'Penguin',
  'Food & Drink: General'],
 ['28',
  'Kite Runner,The',
  'Hosseini, Khaled',
  '1,629,119',
  'Bloomsbury',
  'General & Literary Fiction'],
 ['29',
  'One Day',
  'Nicholls, David',
  '1,616,068',
  'Hodder & Stoughton',
  'General & Literary Fiction'],
 ['30',
  'Thousand Splendid Suns,A',
  'Hosseini, Khaled',
  '1,583,992',
  'Bloomsbury',
  'General & Literary Fiction'],
 ['31',
  "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
  'Larsson, Stieg',
  '1,555,135',
  'Quercus',
  'Crime, Thriller & Adventure'],
 ['32',
  "Time Traveler's Wife,The",
  'Niffenegger, Audrey',
  '1,546,886',
  'Random House',
  'General & Literary Fiction'],
 ['33',
  'Atonement',
  'McEwan, Ian',
  '1,539,428',
  'Random House',
  'General & Literary Fiction'],
 ['34',
  "Bridget Jones's Diary:A Novel",
  'Fielding, Helen',
  '1,508,205',
  'Pan Macmillan',
  'General & Literary Fiction'],
 ['35',
  'World According to Clarkson,The',
  'Clarkson, Jeremy',
  '1,489,403',
  'Penguin',
  'Humour: Collections & General'],
 ['36',
  "Captain Corelli's Mandolin",
  'Bernieres, Louis de',
  '1,352,318',
  'Random House',
  'General & Literary Fiction'],
 ['37',
  'Sound of Laughter,The',
  'Kay, Peter',
  '1,310,207',
  'Random House',
  'Autobiography: General'],
 ['38',
  'Life of Pi',
  'Martel, Yann',
  '1,310,176',
  'Canongate',
  'General & Literary Fiction'],
 ['39',
  'Billy Connolly',
  'Stephenson, Pamela',
  '1,231,957',
  'HarperCollins',
  'Biography: The Arts'],
 ['40',
  'Child Called It,A',
  'Pelzer, Dave',
  '1,217,712',
  'Orion',
  'Autobiography: General'],
 ['41',
  "Gruffalo's Child,The",
  'Donaldson, Julia',
  '1,208,711',
  'Pan Macmillan',
  'Picture Books'],
 ['42',
  "Angela's Ashes:A Memoir of a Childhood",
  'McCourt, Frank',
  '1,204,058',
  'HarperCollins',
  'Autobiography: General'],
 ['43',
  'Birdsong',
  'Faulks, Sebastian',
  '1,184,967',
  'Random House',
  'General & Literary Fiction'],
 ['44',
  'Northern Lights:His Dark Materials S.',
  'Pullman, Philip',
  '1,181,503',
  'Scholastic Ltd.',
  'Young Adult Fiction'],
 ['45',
  'Labyrinth',
  'Mosse, Kate',
  '1,181,093',
  'Orion',
  'General & Literary Fiction'],
 ['46',
  'Harry Potter and the Half-blood Prince',
  'Rowling, J.K.',
  '1,153,181',
  'Bloomsbury',
  'Science Fiction & Fantasy'],
 ['47',
  'Help,The',
  'Stockett, Kathryn',
  '1,132,336',
  'Penguin',
  'General & Literary Fiction'],
 ['48',
  'Man and Boy',
  'Parsons, Tony',
  '1,130,802',
  'HarperCollins',
  'General & Literary Fiction'],
 ['49',
  'Memoirs of a Geisha',
  'Golden, Arthur',
  '1,126,337',
  'Random House',
  'General & Literary Fiction'],
 ['50',
  "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
  'McCall Smith, Alexander',
  '1,115,549',
  'Little, Brown Book',
  'Crime, Thriller & Adventure'],
 ['51',
  'Island,The',
  'Hislop, Victoria',
  '1,108,328',
  'Headline',
  'General & Literary Fiction'],
 ['52',
  'PS, I Love You',
  'Ahern, Cecelia',
  '1,107,379',
  'HarperCollins',
  'General & Literary Fiction'],
 ['53',
  'You are What You Eat:The Plan That Will Change Your Life',
  'McKeith, Gillian',
  '1,104,403',
  'Penguin',
  'Fitness & Diet'],
 ['54',
  'Shadow of the Wind,The',
  'Zafon, Carlos Ruiz',
  '1,092,349',
  'Orion',
  'General & Literary Fiction'],
 ['55',
  'Tales of Beedle the Bard,The',
  'Rowling, J.K.',
  '1,090,847',
  'Bloomsbury',
  "Children's Fiction"],
 ['56',
  'Broker,The',
  'Grisham, John',
  '1,087,262',
  'Random House',
  'Crime, Thriller & Adventure'],
 ['57',
  "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
  'Atkins, Robert C.',
  '1,054,196',
  'Random House',
  'Fitness & Diet'],
 ['58',
  'Subtle Knife,The:His Dark Materials S.',
  'Pullman, Philip',
  '1,037,160',
  'Scholastic Ltd.',
  'Young Adult Fiction'],
 ['59',
  'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
  'Truss, Lynne',
  '1,023,688',
  'Profile Books Group',
  'Usage & Writing Guides'],
 ['60',
  "Delia's How to Cook:(Bk.1)",
  'Smith, Delia',
  '1,015,956',
  'Random House',
  'Food & Drink: General'],
 ['61',
  'Chocolat',
  'Harris, Joanne',
  '1,009,873',
  'Transworld',
  'General & Literary Fiction'],
 ['62',
  'Boy in the Striped Pyjamas,The',
  'Boyne, John',
  '1,004,414',
  'Random House Childrens Books G',
  'Young Adult Fiction'],
 ['63',
  "My Sister's Keeper",
  'Picoult, Jodi',
  '1,003,780',
  'Hodder & Stoughton',
  'General & Literary Fiction'],
 ['64',
  'Amber Spyglass,The:His Dark Materials S.',
  'Pullman, Philip',
  '1,002,314',
  'Scholastic Ltd.',
  'Young Adult Fiction'],
 ['65',
  'To Kill a Mockingbird',
  'Lee, Harper',
  '998,213',
  'Random House',
  'General & Literary Fiction'],
 ['66',
  'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
  'Gray, John',
  '992,846',
  'HarperCollins',
  'Popular Culture & Media: General Interest'],
 ['67',
  'Dear Fatty',
  'French, Dawn',
  '986,753',
  'Random House',
  'Autobiography: The Arts'],
 ['68',
  'Short History of Tractors in Ukrainian,A',
  'Lewycka, Marina',
  '986,115',
  'Penguin',
  'General & Literary Fiction'],
 ['69',
  'Hannibal',
  'Harris, Thomas',
  '970,509',
  'Random House',
  'Crime, Thriller & Adventure'],
 ['70',
  'Lord of the Rings,The',
  'Tolkien, J. R. R.',
  '967,466',
  'HarperCollins',
  'Science Fiction & Fantasy'],
 ['71',
  'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
  'Moore, Michael',
  '963,353',
  'Penguin',
  'Current Affairs & Issues'],
 ['72',
  'Interpretation of Murder,The',
  'Rubenfeld, Jed',
  '962,515',
  'Headline',
  'Crime, Thriller & Adventure'],
 ['73',
  'Sharon Osbourne Extreme:My Autobiography',
  'Osbourne, Sharon',
  '959,496',
  'Little, Brown Book',
  'Autobiography: The Arts'],
 ['74',
  'Alchemist,The:A Fable About Following Your Dream',
  'Coelho, Paulo',
  '956,114',
  'HarperCollins',
  'General & Literary Fiction'],
 ['75',
  "At My Mother's Knee ...:and Other Low Joints",
  "O'Grady, Paul",
  '945,640',
  'Transworld',
  'Autobiography: The Arts'],
 ['76',
  'Notes from a Small Island',
  'Bryson, Bill',
  '931,312',
  'Transworld',
  'Travel Writing'],
 ['77',
  'Return of the Naked Chef,The',
  'Oliver, Jamie',
  '925,425',
  'Penguin',
  'Food & Drink: General'],
 ['78',
  'Bridget Jones: The Edge of Reason',
  'Fielding, Helen',
  '924,695',
  'Pan Macmillan',
  'General & Literary Fiction'],
 ['79',
  "Jamie's Italy",
  'Oliver, Jamie',
  '906,968',
  'Penguin',
  'National & Regional Cuisine'],
 ['80',
  'I Can Make You Thin',
  'McKenna, Paul',
  '905,086',
  'Transworld',
  'Fitness & Diet'],
 ['81',
  'Down Under',
  'Bryson, Bill',
  '890,847',
  'Transworld',
  'Travel Writing'],
 ['82',
  'Summons,The',
  'Grisham, John',
  '869,671',
  'Random House',
  'Crime, Thriller & Adventure'],
 ['83',
  'Small Island',
  'Levy, Andrea',
  '869,659',
  'Headline',
  'General & Literary Fiction'],
 ['84',
  'Nigella Express',
  'Lawson, Nigella',
  '862,602',
  'Random House',
  'Food & Drink: General'],
 ['85',
  'Brick Lane',
  'Ali, Monica',
  '856,540',
  'Transworld',
  'General & Literary Fiction'],
 ['86',
  "Memory Keeper's Daughter,The",
  'Edwards, Kim',
  '845,858',
  'Penguin',
  'General & Literary Fiction'],
 ['87',
  'Room on the Broom',
  'Donaldson, Julia',
  '842,535',
  'Pan Macmillan',
  'Picture Books'],
 ['88',
  'About a Boy',
  'Hornby, Nick',
  '828,215',
  'Penguin',
  'General & Literary Fiction'],
 ['89',
  'My Booky Wook',
  'Brand, Russell',
  '820,563',
  'Hodder & Stoughton',
  'Autobiography: The Arts'],
 ['90',
  'God Delusion,The',
  'Dawkins, Richard',
  '816,907',
  'Transworld',
  'Popular Science'],
 ['91',
  '"Beano" Annual,The',
  '0',
  '816,585',
  'D.C. Thomson',
  "Children's Annuals"],
 ['92',
  'White Teeth',
  'Smith, Zadie',
  '815,586',
  'Penguin',
  'General & Literary Fiction'],
 ['93',
  'House at Riverton,The',
  'Morton, Kate',
  '814,370',
  'Pan Macmillan',
  'General & Literary Fiction'],
 ['94',
  'Book Thief,The',
  'Zusak, Markus',
  '809,641',
  'Transworld',
  'General & Literary Fiction'],
 ['95',
  'Nights of Rain and Stars',
  'Binchy, Maeve',
  '808,900',
  'Orion',
  'General & Literary Fiction'],
 ['96',
  'Ghost,The',
  'Harris, Robert',
  '807,311',
  'Random House',
  'General & Literary Fiction'],
 ['97',
  'Happy Days with the Naked Chef',
  'Oliver, Jamie',
  '794,201',
  'Penguin',
  'Food & Drink: General'],
 ['98',
  'Hunger Games,The:Hunger Games Trilogy',
  'Collins, Suzanne',
  '792,187',
  'Scholastic Ltd.',
  'Young Adult Fiction'],
 ['99',
  "Lost Boy,The:A Foster Child's Search for the Love of a Family",
  'Pelzer, Dave',
  '791,507',
  'Orion',
  'Biography: General'],
 ['100',
  "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours",
  'Oliver, Jamie',
  '791,095',
  'Penguin',
  'Food & Drink: General']]

In [ ]:
Q7:Scrape the details most watched tv series of all time from imdb.com.   
Url = https://www.imdb.com/list/ls095964455/ You have 
to find the following details:   
A) Name   
B) Year span   
C) Genre   
D) Run time   
E) Ratings   
F) Votes

In [14]:
driver = webdriver.Chrome()
driver.get('https://www.imdb.com/list/ls095964455/')

In [ ]:
Getting below error 


The requested URL was not found on our server. Go to the homepage

error 404

In [ ]:
Q8:Details of Datasets from UCI machine learning repositories.   
Url = https://archive.ics.uci.edu/  You 
have to find the following details:   
A) Dataset name   
B) Data type   
C) Task   
D) Attribute type   
E) No of instances   
F) No of attribute G) Year

In [15]:
driver = webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')

In [16]:
data_set = driver.find_element(By.XPATH,'//a[@class="btn-primary btn"]')
data_set.click()
time.sleep(2)

In [17]:
data_url=[]
start =0
end =61
for page in range (start,end):
    url=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in url:
        data_url.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    next_button.click()
    time.sleep(2)

In [18]:
len(data_url)

610

In [19]:
data_set_name=[]
data_type=[]
task=[]
atri_type=[]
no_of_instance=[]
no_of_attribute=[]
year=[]

In [21]:
for url in data_url:
    driver.get(url)
    time.sleep(2)
    
    try:
        datas=driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        data_set_name.append(datas.text)
    except NoSuchElementException:
        data_set_name.append('-')
    try:
        d_type=driver.find_element(By.XPATH,'//p[@class="text-md"]')
        data_type.append(d_type.text)
    except NoSuchElementException:
        data_type.append('-')
    try:
        tsk=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p')
        task.append(tsk.text)
    except NoSuchElementException:
        task.append('-')
    try:
        attribute=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p')
        atri_type.append(attribute.text)
    except NoSuchElementException:
        atri_type.append('-')
    try:
        ins=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p')
        no_of_instance.append(ins.text)
    except NoSuchElementException:
        no_of_instance.append('-')
    try:
        atr=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[6]/p')
        no_of_attribute.append(atr.text)
    except NoSuchElementException:
        no_of_attribute.append('-')
    try:
        yr=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/h2')
        year.append(yr.text)
    except NoSuchElementException:
        year.append('-')

In [33]:
data_set = pd.DataFrame({'Dataset_name':data_set_name,'Data_Type':data_type,'Task':task,'Attribute_type':atri_type,
                          'No_of_instances':no_of_instance,'No_of_attribute':no_of_attribute})

data_set

,Dataset_name,Data_Type,Task,Attribute_type,No_of_instances,No_of_attribute
0,Iris,Tabular,Classification,Real,150,4
1,Iris,Tabular,Classification,Real,150,4
2,Dry Bean,Multivariate,Classification,"Integer, Real",13611,16
3,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,13
4,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3810,7
...,...,...,...,...,...,...
606,Coil 1999 Competition Data,Multivariate,-,"Categorical, Real",340,-
607,Turkish Spam V01,Text,Classification,-,826,2
608,: Simulated Data set of Iraqi tourism places,Multivariate,"Classification, Clustering",-,232,16
609,NYSK,"Multivariate, Sequential, Text",Clustering,-,10421,7
610,Firm-Teacher_Clave-Direction_Classification,Multivariate,Classification,-,10800,20